# Model Experimentation — ResNet50 vs HRNet × Frame Count × Bird

Compare DeepLabCut training performance across:

- **Architectures**: ResNet-50, HRNet-W32
- **Training frame counts**: 400, 800, 1400
- **Birds**: Miguel, DavidBowie, Endive

A fixed holdout of **200 frames** (per bird) is reserved with a separate seed so RMSE and training-time comparisons remain fair across all 18 runs (2 archs × 3 frame counts × 3 birds).

In [1]:
import os
import glob
import json
import logging
import random
import time
from dataclasses import dataclass, asdict, field
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

import sys
sys.path.insert(0, str(Path(".").resolve()))   # so DLCsupport.py is importable

import DLCsupport as dlcs
from DLCsupport import (
    as_posix_str,
    validate_path_exists,
    find_latest_snapshot,
    load_bodyparts,
    create_combined_project_if_missing,
    build_combined_dataset,
)

import deeplabcut
import xrommtools

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

print(f"Seed        : {SEED}")
print(f"NumPy       : {np.__version__}")
print(f"Pandas      : {pd.__version__}")
print(f"DeepLabCut  : {deeplabcut.__version__}")

Loading DLC 3.0.0rc13...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Seed        : 42
NumPy       : 1.23.5
Pandas      : 2.3.3
DeepLabCut  : 3.0.0rc13

In [ ]:
## 2. Global Constants
# Centralize seeds, frame budgets, architecture names, and safety toggles.

In [2]:
# Workspace root (one level above Code-Testing/)
ROOT = Path("..")

TASK         = "Canari"
EXPERIMENTER = "Tyler"

# Frame counts to evaluate — one combined project is created per (bird, n)
FRAME_COUNTS  = [200, 400, 800, 1400]

# Frames held out for evaluation. Built once per bird with HOLDOUT_SEED
# so the exact same 200 frames are used across every training comparison.
HOLDOUT_N    = 200
HOLDOUT_SEED = 999   # kept different from TRAIN_SEED on purpose
TRAIN_SEED   = SEED  # reproducible training-frame selection

# DLC PyTorch backbone names to compare
ARCHITECTURES = ["resnet_50"]

EPOCHS_SMOKE = 2
EPOCHS_FULL  = 200

# Safety toggles  — flip to True to actually run training / analysis
RUN_TRAINING      = False
RUN_VIDEO_ANALYSIS = False
USE_FULL_EPOCHS   = False

print("Global constants ready.")
print(f"  Frame counts  : {FRAME_COUNTS}")
print(f"  Architectures : {ARCHITECTURES}")
print(f"  Holdout N     : {HOLDOUT_N}  (seed {HOLDOUT_SEED})")
print(f"  Train seed    : {TRAIN_SEED}")
print(f"  Epochs        : {EPOCHS_FULL if USE_FULL_EPOCHS else EPOCHS_SMOKE} ({'FULL' if USE_FULL_EPOCHS else 'SMOKE'})")

Global constants ready.
  Frame counts  : [200, 400, 800, 1400]
  Architectures : ['resnet_50']
  Holdout N     : 200  (seed 999)
  Train seed    : 42
  Epochs        : 2 (SMOKE)

## 3. Per-Bird Configuration

Each bird gets its own cell with all necessary paths.
Update the date-stamped subfolder (e.g. `Canari-Tyler-2026-03-31`) if you create new single-camera projects on a different date.

In [8]:
# ── Miguel ─────────────────────────────────────────────────────────────────
MIGUEL_ROOT = ROOT / "DeepLabCut" / "Miguel"

MIGUEL_CAM1_CONFIG = (
    MIGUEL_ROOT / "TestData" / "Canari_cam1_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)
MIGUEL_CAM2_CONFIG = (
    MIGUEL_ROOT / "TestData" / "Canari_cam2_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)

# Root folder that will contain all Miguel combined-training sub-projects
MIGUEL_COMBINED_BASE = MIGUEL_ROOT / "TestData"

MIGUEL_DATA_PATH    = MIGUEL_ROOT / "trainingdata"
MIGUEL_DATASET_NAME = "Canari"

# Any existing .avi used only to satisfy DLC project-creation API
MIGUEL_DUMMY_VIDEO  = (
    MIGUEL_ROOT / "trainingdata" / "Miguel_20250816_F6"
    / "MiguelF6_20250816_Cam1_short.avi"
)

# Videos used for evaluation (not seen during training)
MIGUEL_TEST_VIDEO_CAM1 = (
    MIGUEL_ROOT / "newdata" / "Miguel20260401Trial6_Cam1"
    / "MiguelF6_20250816_Cam1_short.avi"
)
MIGUEL_TEST_VIDEO_CAM2 = (
    MIGUEL_ROOT / "newdata" / "Miguel20260401Trial6_Cam2"
    / "MiguelF6_20250816_Cam2_short.avi"
)

print("Miguel paths:")
print("  Cam1 config :", MIGUEL_CAM1_CONFIG)
print("  Cam2 config :", MIGUEL_CAM2_CONFIG)
print("  Data path   :", MIGUEL_DATA_PATH)
print("  Dummy video :", MIGUEL_DUMMY_VIDEO)
print("  Test cam1   :", MIGUEL_TEST_VIDEO_CAM1)
print("  Test cam2   :", MIGUEL_TEST_VIDEO_CAM2)

Miguel paths:
  Cam1 config : ..\DeepLabCut\Miguel\TestData\Canari_cam1_training\Canari-Tyler-2026-03-31\config.yaml
  Cam2 config : ..\DeepLabCut\Miguel\TestData\Canari_cam2_training\Canari-Tyler-2026-03-31\config.yaml
  Data path   : ..\DeepLabCut\Miguel\trainingdata
  Dummy video : ..\DeepLabCut\Miguel\trainingdata\Miguel_20250816_F6\MiguelF6_20250816_Cam1_short.avi
  Test cam1   : ..\DeepLabCut\Miguel\newdata\Miguel20260401Trial6_Cam1\MiguelF6_20250816_Cam1_short.avi
  Test cam2   : ..\DeepLabCut\Miguel\newdata\Miguel20260401Trial6_Cam2\MiguelF6_20250816_Cam2_short.avi

In [3]:
# ── DavidBowie ─────────────────────────────────────────────────────────────
# NOTE: Mirror Miguel's folder tree under DeepLabCut/DavidBowie/.
#       Update the date-stamped subfolder once the single-camera projects exist.
DAVIDBOWIE_ROOT = ROOT / "DeepLabCut" / "DavidBowie"

DAVIDBOWIE_CAM1_CONFIG = (
    DAVIDBOWIE_ROOT / "TestData" / "Canari_cam1_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)
DAVIDBOWIE_CAM2_CONFIG = (
    DAVIDBOWIE_ROOT / "TestData" / "Canari_cam2_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)

DAVIDBOWIE_COMBINED_BASE = DAVIDBOWIE_ROOT / "TestData"

DAVIDBOWIE_DATA_PATH    = DAVIDBOWIE_ROOT / "trainingdata"
DAVIDBOWIE_DATASET_NAME = "Canari"

# Replace with the actual training video once it exists
DAVIDBOWIE_DUMMY_VIDEO  = (
    DAVIDBOWIE_ROOT / "trainingdata" / "DavidBowie_20250828_F17"
    / "DB17_Cam1.avi"
)

DAVIDBOWIE_TEST_VIDEO_CAM1 = (
    DAVIDBOWIE_ROOT / "newdata" / "DavidBowie_20250828_F17"
    / "DB17_Cam1.avi"
)
DAVIDBOWIE_TEST_VIDEO_CAM2 = (
    DAVIDBOWIE_ROOT / "newdata" / "DavidBowie_20250828_F17"
    / "DB17_Cam2.avi"
)

print("DavidBowie paths:")
print("  Cam1 config :", DAVIDBOWIE_CAM1_CONFIG)
print("  Cam2 config :", DAVIDBOWIE_CAM2_CONFIG)
print("  Data path   :", DAVIDBOWIE_DATA_PATH)
print("  Dummy video :", DAVIDBOWIE_DUMMY_VIDEO)
print("  Test cam1   :", DAVIDBOWIE_TEST_VIDEO_CAM1)
print("  Test cam2   :", DAVIDBOWIE_TEST_VIDEO_CAM2)

DavidBowie paths:
  Cam1 config : ..\DeepLabCut\DavidBowie\TestData\Canari_cam1_training\Canari-Tyler-2026-03-31\config.yaml
  Cam2 config : ..\DeepLabCut\DavidBowie\TestData\Canari_cam2_training\Canari-Tyler-2026-03-31\config.yaml
  Data path   : ..\DeepLabCut\DavidBowie\trainingdata
  Dummy video : ..\DeepLabCut\DavidBowie\trainingdata\DavidBowie_20250828_F17\DB17_Cam1.avi
  Test cam1   : ..\DeepLabCut\DavidBowie\newdata\DavidBowie_20250828_F17\DB17_Cam1.avi
  Test cam2   : ..\DeepLabCut\DavidBowie\newdata\DavidBowie_20250828_F17\DB17_Cam2.avi

In [4]:
# ── Endive ──────────────────────────────────────────────────────────────────
# NOTE: Mirror Miguel's folder tree under DeepLabCut/Endive/.
#       Update the date-stamped subfolder once the single-camera projects exist.
ENDIVE_ROOT = ROOT / "DeepLabCut" / "Endive"

ENDIVE_CAM1_CONFIG = (
    ENDIVE_ROOT / "TestData" / "Canari_cam1_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)
ENDIVE_CAM2_CONFIG = (
    ENDIVE_ROOT / "TestData" / "Canari_cam2_training"
    / "Canari-Tyler-2026-03-31" / "config.yaml"
)

ENDIVE_COMBINED_BASE = ENDIVE_ROOT / "TestData"

ENDIVE_DATA_PATH    = ENDIVE_ROOT / "trainingdata"
ENDIVE_DATASET_NAME = "Canari"

# Replace with the actual training video once it exists
ENDIVE_DUMMY_VIDEO  = (
    ENDIVE_ROOT / "trainingdata" / "Endive_20251606_F32"
    / "EndiveF42_20251606_Cam1_short.avi"
)


ENDIVE_TEST_VIDEO_CAM1 = (
    ENDIVE_ROOT / "newdata" / "Endive_20251606_F32"
    / "EndiveF42_20251606_Cam1_short.avi"
)
ENDIVE_TEST_VIDEO_CAM2 = (
    ENDIVE_ROOT / "newdata" / "Endive_20251606_F32"
    / "EndiveF42_20251606_Cam2_short.avi"
)

print("Endive paths:")
print("  Cam1 config :", ENDIVE_CAM1_CONFIG)
print("  Cam2 config :", ENDIVE_CAM2_CONFIG)
print("  Data path   :", ENDIVE_DATA_PATH)
print("  Dummy video :", ENDIVE_DUMMY_VIDEO)
print("  Test cam1   :", ENDIVE_TEST_VIDEO_CAM1)
print("  Test cam2   :", ENDIVE_TEST_VIDEO_CAM2)

Endive paths:
  Cam1 config : ..\DeepLabCut\Endive\TestData\Canari_cam1_training\Canari-Tyler-2026-03-31\config.yaml
  Cam2 config : ..\DeepLabCut\Endive\TestData\Canari_cam2_training\Canari-Tyler-2026-03-31\config.yaml
  Data path   : ..\DeepLabCut\Endive\trainingdata
  Dummy video : ..\DeepLabCut\Endive\trainingdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi
  Test cam1   : ..\DeepLabCut\Endive\newdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi
  Test cam2   : ..\DeepLabCut\Endive\newdata\Endive_20251606_F32\EndiveF42_20251606_Cam2_short.avi

## 4. Bird Registry
Collect all per-bird variables into one dict so the rest of the notebook can iterate without repeating code.

In [5]:
BIRDS = {

    "DavidBowie": {
        "cam1_config"    : DAVIDBOWIE_CAM1_CONFIG,
        "cam2_config"    : DAVIDBOWIE_CAM2_CONFIG,
        "combined_base"  : DAVIDBOWIE_COMBINED_BASE,
        "data_path"      : DAVIDBOWIE_DATA_PATH,
        "dataset_name"   : DAVIDBOWIE_DATASET_NAME,
        "dummy_video"    : DAVIDBOWIE_DUMMY_VIDEO,
        "test_videos"    : [DAVIDBOWIE_TEST_VIDEO_CAM1, DAVIDBOWIE_TEST_VIDEO_CAM2],
    },
    "Endive": {
        "cam1_config"    : ENDIVE_CAM1_CONFIG,
        "cam2_config"    : ENDIVE_CAM2_CONFIG,
        "combined_base"  : ENDIVE_COMBINED_BASE,
        "data_path"      : ENDIVE_DATA_PATH,
        "dataset_name"   : ENDIVE_DATASET_NAME,
        "dummy_video"    : ENDIVE_DUMMY_VIDEO,
        "test_videos"    : [ENDIVE_TEST_VIDEO_CAM1, ENDIVE_TEST_VIDEO_CAM2],
    },
}

print(f"Registered {len(BIRDS)} birds: {list(BIRDS)}")

Registered 2 birds: ['DavidBowie', 'Endive']

## 5. Create Combined Projects

One combined DLC project is created for **each (bird, frame-count) pair** — 9 training projects total.
A separate **holdout project** (200 frames) is also created per bird so evaluation frames are never in any training set.

All 12 projects are stored in `combined_configs`, keyed by `(bird_name, nframes)` or `(bird_name, "holdout")`.

In [ ]:
# combined_configs[(bird_name, nframes)]   -> Path to config.yaml  (training projects)
# combined_configs[(bird_name, "holdout")] -> Path to config.yaml  (evaluation project)
combined_configs: dict = {}

for bird_name, bird_cfg in BIRDS.items():
    base = bird_cfg["combined_base"]   # e.g. .../Miguel/TestData/
    dummy = bird_cfg["dummy_video"]


    # ── Training projects — one per frame count ───────────────────────────────
    for n in FRAME_COUNTS:
        cfg_path = create_combined_project_if_missing(
            task=TASK,
            experimenter=EXPERIMENTER,
            combined_project_root=base / f"Canari_combined_n{n}",
            dummy_video=dummy,
        )
        combined_configs[(bird_name, n)] = cfg_path

    print(f"{bird_name}: {len(FRAME_COUNTS)} training + 1 holdout projects ready.")

print(f"\nTotal combined configs registered: {len(combined_configs)}")
for key, path in combined_configs.items():
    print(f"  {key[0]:12s}  {'holdout' if key[1] == 'holdout' else f'n={key[1]:>4}'}  ->  {path}")

#FIXME: update to include edit config command from deeplabcut, input config path and disctionary {bodyparts: ["bodypart1", "bodypart2", ...]}

Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\trainingdata\DavidBowie_20250828_F17\DB17_cam1.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\trainingdata\DavidBowie_20250828_F17\DB17_cam1.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\trainingdata\DavidBowie_20250828_F17\DB17_cam1.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\trainingdata\DavidBowie_20250828_F17\DB17_cam1.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos\DB17_cam1.avi

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml

Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
DavidBowie: 4 training + 1 holdout projects ready.
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\trainingdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\trainingdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\trainingdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\training-datasets"
Created "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models"
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): copying the video instead.

INFO | Created combined project: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml

C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\trainingdata\Endive_20251606_F32\EndiveF42_20251606_Cam1_short.avi copied to C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\videos\EndiveF42_20251606_Cam1_short.avi
Generated "C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml"

A new project with name Canari-Tyler-2026-04-08 is created at C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400 and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Endive: 4 training + 1 holdout projects ready.

Total combined configs registered: 8
  DavidBowie    n= 200  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml
  DavidBowie    n= 400  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml
  DavidBowie    n= 800  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml
  DavidBowie    n=1400  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml
  Endive        n= 200  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\config.yaml
  Endive        n= 400  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\config.yaml
  Endive        n= 800  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\config.yaml
  Endive        n=1400  ->  C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\config.yaml

## 6. Build Combined Datasets

Build **9 training datasets** (3 birds × 3 frame counts) plus **3 holdout datasets** (one per bird, 200 frames each).

**Holdout strategy**:  
- Holdout frames are sampled with `HOLDOUT_SEED = 999`.  
- Training frames are sampled with `TRAIN_SEED = 42`.  
- Because the seeds differ, overlap between holdout and training pools is negligible. The same holdout frames will be produced identically every time this cell is re-run.

In [7]:
dataset_build_log = []   # records what was (or would be) built

for bird_name, bird_cfg in BIRDS.items():

    for n in FRAME_COUNTS:
        train_cfg = combined_configs[(bird_name, n)]
        print(f"[{bird_name}] Building training dataset (n={n} frames, seed={TRAIN_SEED}) ...")
        build_combined_dataset(
            combined_config     = train_cfg,
            data_path           = bird_cfg["data_path"],
            dataset_name        = bird_cfg["dataset_name"],
            experimenter        = EXPERIMENTER,
            nframes             = n,
            frame_selection_seed= TRAIN_SEED,
        )
        dataset_build_log.append({"bird": bird_name, "split": "train", "nframes": n, "config": str(train_cfg)})

print(f"\n{'─'*60}")
print(f"Dataset builds complete: {len([r for r in dataset_build_log if r['split']=='train'])} training  "
      f"+ {len([r for r in dataset_build_log if r['split']=='holdout'])} holdout")
pd.DataFrame(dataset_build_log)[["bird", "split", "nframes"]].to_string(index=False) \
    and print(pd.DataFrame(dataset_build_log)[["bird", "split", "nframes"]].to_string(index=False))

INFO | Frame selection seed set to 42

[DavidBowie] Building training dataset (n=200 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[DavidBowie] Building training dataset (n=400 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[DavidBowie] Building training dataset (n=800 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[DavidBowie] Building training dataset (n=1400 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[Endive] Building training dataset (n=200 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[Endive] Building training dataset (n=400 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[Endive] Building training dataset (n=800 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...

INFO | Frame selection seed set to 42

...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset
[Endive] Building training dataset (n=1400 frames, seed=42) ...
Extracting camera 1 trial images and 2D points...
Extracting camera 2 trial images and 2D points...
...done.
Training data extracted to projectpath/labeled-data. Now use deeplabcut.create_training_dataset

────────────────────────────────────────────────────────────
Dataset builds complete: 8 training  + 0 holdout
      bird split  nframes
DavidBowie train      200
DavidBowie train      400
DavidBowie train      800
DavidBowie train     1400
    Endive train      200
    Endive train      400
    Endive train      800
    Endive train     1400

In [8]:
image_exts = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}
dataset_frame_counts = []

for (bird_name, split_key), config_path in sorted(
    combined_configs.items(),
    key=lambda item: (item[0][0], str(item[0][1])),
):
    labeled_dir = Path(config_path).parent / "labeled-data"
    image_paths = [
        p for p in labeled_dir.rglob("*")
        if p.is_file() and p.suffix.lower() in image_exts
    ]

    unique_image_files = {
        p.relative_to(labeled_dir).as_posix()
        for p in image_paths
    }

    # Collapse cam1/cam2 pairs to one logical frame ID when possible.
    unique_logical_frames = {
        p.stem.replace("_cam1_", "_cam_").replace("_cam2_", "_cam_")
        for p in image_paths
    }

    dataset_frame_counts.append({
        "bird": bird_name,
        "split": "holdout" if split_key == "holdout" else "train",
        "nframes": HOLDOUT_N if split_key == "holdout" else split_key,
        "unique_image_files": len(unique_image_files),
        "unique_logical_frames": len(unique_logical_frames),
        "labeled_data_dir": str(labeled_dir),
    })

dataset_frame_counts_df = pd.DataFrame(dataset_frame_counts).sort_values(
    ["bird", "split", "nframes"]
)

print(
    dataset_frame_counts_df[
        ["bird", "split", "nframes", "unique_image_files", "unique_logical_frames"]
    ].to_string(index=False)
)

dataset_frame_counts_df

      bird split  nframes  unique_image_files  unique_logical_frames
DavidBowie train      200                 400                    200
DavidBowie train      400                 800                    400
DavidBowie train      800                1600                    800
DavidBowie train     1400                2800                   1400
    Endive train      200                 400                    200
    Endive train      400                 800                    400
    Endive train      800                1600                    800
    Endive train     1400                2800                   1400

,bird,split,nframes,unique_image_files,unique_logical_frames,labeled_data_dir
1,DavidBowie,train,200,400,200,C:\Users\Salle-Cineradio\Documents\MachineLear...
2,DavidBowie,train,400,800,400,C:\Users\Salle-Cineradio\Documents\MachineLear...
3,DavidBowie,train,800,1600,800,C:\Users\Salle-Cineradio\Documents\MachineLear...
0,DavidBowie,train,1400,2800,1400,C:\Users\Salle-Cineradio\Documents\MachineLear...
5,Endive,train,200,400,200,C:\Users\Salle-Cineradio\Documents\MachineLear...
6,Endive,train,400,800,400,C:\Users\Salle-Cineradio\Documents\MachineLear...
7,Endive,train,800,1600,800,C:\Users\Salle-Cineradio\Documents\MachineLear...
4,Endive,train,1400,2800,1400,C:\Users\Salle-Cineradio\Documents\MachineLear...

In [9]:
[element for element in unique_image_files if element.__contains__('001')]

['Canari/Endive_20251606_F32_cam1_0016.png',
 'Canari/Endive_20251606_F32_cam2_0013.png',
 'Canari/Endive_20251606_F32_cam2_0001.png',
 'Canari/Endive_20251606_F32_cam1_0010.png',
 'Canari/Endive_20251606_F32_cam2_0010.png',
 'Canari/Endive_20251606_F32_cam1_0018.png',
 'Canari/Endive_20251606_F32_cam1_0001.png',
 'Canari/Endive_20251606_F32_cam2_0018.png',
 'Canari/Endive_20251606_F32_cam1_0013.png',
 'Canari/Endive_20251606_F32_cam2_0016.png']

In [10]:
unique_image_files

{'Canari/Endive_20251606_F32_cam1_3238.png',
 'Canari/Endive_20251606_F32_cam2_0156.png',
 'Canari/Endive_20251606_F32_cam2_1465.png',
 'Canari/Endive_20251606_F32_cam2_2053.png',
 'Canari/Endive_20251606_F32_cam2_2837.png',
 'Canari/Endive_20251606_F32_cam2_3665.png',
 'Canari/Endive_20251606_F32_cam1_1754.png',
 'Canari/Endive_20251606_F32_cam2_1083.png',
 'Canari/Endive_20251606_F32_cam1_1005.png',
 'Canari/Endive_20251606_F32_cam2_2483.png',
 'Canari/Endive_20251606_F32_cam1_1542.png',
 'Canari/Endive_20251606_F32_cam2_3158.png',
 'Canari/Endive_20251606_F32_cam2_1038.png',
 'Canari/Endive_20251606_F32_cam1_1048.png',
 'Canari/Endive_20251606_F32_cam2_1678.png',
 'Canari/Endive_20251606_F32_cam1_1901.png',
 'Canari/Endive_20251606_F32_cam2_3082.png',
 'Canari/Endive_20251606_F32_cam1_0579.png',
 'Canari/Endive_20251606_F32_cam1_2701.png',
 'Canari/Endive_20251606_F32_cam1_1076.png',
 'Canari/Endive_20251606_F32_cam2_3375.png',
 'Canari/Endive_20251606_F32_cam2_3353.png',
 'Canari/Endive_20251606_F32_cam2_0599.png',
 'Canari/Endive_20251606_F32_cam1_0554.png',
 'Canari/Endive_20251606_F32_cam2_3653.png',
 'Canari/Endive_20251606_F32_cam2_0810.png',
 'Canari/Endive_20251606_F32_cam1_0734.png',
 'Canari/Endive_20251606_F32_cam2_2558.png',
 'Canari/Endive_20251606_F32_cam2_2119.png',
 'Canari/Endive_20251606_F32_cam1_2986.png',
 'Canari/Endive_20251606_F32_cam1_2857.png',
 'Canari/Endive_20251606_F32_cam1_3652.png',
 'Canari/Endive_20251606_F32_cam2_1706.png',
 'Canari/Endive_20251606_F32_cam2_3559.png',
 'Canari/Endive_20251606_F32_cam1_1410.png',
 'Canari/Endive_20251606_F32_cam1_0830.png',
 'Canari/Endive_20251606_F32_cam2_3471.png',
 'Canari/Endive_20251606_F32_cam2_1237.png',
 'Canari/Endive_20251606_F32_cam2_2446.png',
 'Canari/Endive_20251606_F32_cam2_2631.png',
 'Canari/Endive_20251606_F32_cam1_0369.png',
 'Canari/Endive_20251606_F32_cam2_3335.png',
 'Canari/Endive_20251606_F32_cam1_2954.png',
 'Canari/Endive_20251606_F32_cam1_3278.png',
 'Canari/Endive_20251606_F32_cam2_3276.png',
 'Canari/Endive_20251606_F32_cam2_2177.png',
 'Canari/Endive_20251606_F32_cam2_3114.png',
 'Canari/Endive_20251606_F32_cam1_3028.png',
 'Canari/Endive_20251606_F32_cam2_1406.png',
 'Canari/Endive_20251606_F32_cam1_1963.png',
 'Canari/Endive_20251606_F32_cam1_0758.png',
 'Canari/Endive_20251606_F32_cam1_0503.png',
 'Canari/Endive_20251606_F32_cam1_2084.png',
 'Canari/Endive_20251606_F32_cam2_1549.png',
 'Canari/Endive_20251606_F32_cam1_0021.png',
 'Canari/Endive_20251606_F32_cam2_2489.png',
 'Canari/Endive_20251606_F32_cam2_1333.png',
 'Canari/Endive_20251606_F32_cam1_0044.png',
 'Canari/Endive_20251606_F32_cam1_3059.png',
 'Canari/Endive_20251606_F32_cam1_1137.png',
 'Canari/Endive_20251606_F32_cam2_0325.png',
 'Canari/Endive_20251606_F32_cam2_1941.png',
 'Canari/Endive_20251606_F32_cam2_2635.png',
 'Canari/Endive_20251606_F32_cam2_3596.png',
 'Canari/Endive_20251606_F32_cam2_2127.png',
 'Canari/Endive_20251606_F32_cam2_3392.png',
 'Canari/Endive_20251606_F32_cam2_0043.png',
 'Canari/Endive_20251606_F32_cam1_2165.png',
 'Canari/Endive_20251606_F32_cam1_3325.png',
 'Canari/Endive_20251606_F32_cam2_3635.png',
 'Canari/Endive_20251606_F32_cam1_1916.png',
 'Canari/Endive_20251606_F32_cam1_0977.png',
 'Canari/Endive_20251606_F32_cam1_0358.png',
 'Canari/Endive_20251606_F32_cam1_0145.png',
 'Canari/Endive_20251606_F32_cam1_3235.png',
 'Canari/Endive_20251606_F32_cam1_2848.png',
 'Canari/Endive_20251606_F32_cam2_1552.png',
 'Canari/Endive_20251606_F32_cam2_0724.png',
 'Canari/Endive_20251606_F32_cam1_0028.png',
 'Canari/Endive_20251606_F32_cam1_2140.png',
 'Canari/Endive_20251606_F32_cam2_0879.png',
 'Canari/Endive_20251606_F32_cam2_0840.png',
 'Canari/Endive_20251606_F32_cam1_1323.png',
 'Canari/Endive_20251606_F32_cam1_2435.png',
 'Canari/Endive_20251606_F32_cam1_2669.png',
 'Canari/Endive_20251606_F32_cam1_0198.png',
 'Canari/Endive_20251606_F32_cam1_2477.png',
 'Canari/Endive_20251606_F32_cam1_0016.png',
 'Canari/Endive_20251606_F32_cam1_2010.png',
 'Canari/Endive_20251606_F32_cam1_3294.png',
 'Canari/Endive_20251606_F32_cam2_1849.png',
 'Canari/Endive_20251606_F32_cam2_0758.png',
 'Canari/Endive_20251606_F32_cam1_1447.png',
 'Canari/Endive_20251606_F32_cam1_2098.png',
 'Canari/Endive_20251606_F32_cam2_3141.png',
 'Canari/Endive_20251606_F32_cam1_2696.png',
 'Canari/Endive_20251606_F32_cam1_0664.png',
 'Canari/Endive_20251606_F32_cam2_0988.png',
 'Canari/Endive_20251606_F32_cam1_0862.png',
 'Canari/Endive_20251606_F32_cam2_0393.png',
 'Canari/Endive_20251606_F32_cam2_2158.png',
 'Canari/Endive_20251606_F32_cam1_1768.png',
 'Canari/Endive_20251606_F32_cam2_0777.png',
 'Canari/Endive_20251606_F32_cam2_1529.png',
 'Canari/Endive_20251606_F32_cam1_1897.png',
 'Canari/Endive_20251606_F32_cam1_0599.png',
 'Canari/Endive_20251606_F32_cam2_2664.png',
 'Canari/Endive_20251606_F32_cam1_0947.png',
 'Canari/Endive_20251606_F32_cam2_1854.png',
 'Canari/Endive_20251606_F32_cam1_0400.png',
 'Canari/Endive_20251606_F32_cam2_3188.png',
 'Canari/Endive_20251606_F32_cam1_1109.png',
 'Canari/Endive_20251606_F32_cam2_2477.png',
 'Canari/Endive_20251606_F32_cam2_3411.png',
 'Canari/Endive_20251606_F32_cam1_0640.png',
 'Canari/Endive_20251606_F32_cam2_2590.png',
 'Canari/Endive_20251606_F32_cam1_2251.png',
 'Canari/Endive_20251606_F32_cam2_2024.png',
 'Canari/Endive_20251606_F32_cam1_2569.png',
 'Canari/Endive_20251606_F32_cam1_0031.png',
 'Canari/Endive_20251606_F32_cam1_3560.png',
 'Canari/Endive_20251606_F32_cam1_1978.png',
 'Canari/Endive_20251606_F32_cam2_2161.png',
 'Canari/Endive_20251606_F32_cam2_2345.png',
 'Canari/Endive_20251606_F32_cam1_0156.png',
 'Canari/Endive_20251606_F32_cam1_3473.png',
 'Canari/Endive_20251606_F32_cam2_2423.png',
 'Canari/Endive_20251606_F32_cam1_2420.png',
 'Canari/Endive_20251606_F32_cam2_1253.png',
 'Canari/Endive_20251606_F32_cam2_1191.png',
 'Canari/Endive_20251606_F32_cam1_1605.png',
 'Canari/Endive_20251606_F32_cam1_2552.png',
 'Canari/Endive_20251606_F32_cam1_0022.png',
 'Canari/Endive_20251606_F32_cam2_3356.png',
 'Canari/Endive_20251606_F32_cam2_3418.png',
 'Canari/Endive_20251606_F32_cam2_3437.png',
 'Canari/Endive_20251606_F32_cam2_0028.png',
 'Canari/Endive_20251606_F32_cam1_1150.png',
 'Canari/Endive_20251606_F32_cam1_2128.png',
 'Canari/Endive_20251606_F32_cam2_3339.png',
 'Canari/Endive_20251606_F32_cam2_0566.png',
 'Canari/Endive_20251606_F32_cam1_3357.png',
 'Canari/Endive_20251606_F32_cam1_0991.png',
 'Canari/Endive_20251606_F32_cam2_0733.png',
 'Canari/Endive_20251606_F32_cam2_0729.png',
 'Canari/Endive_20251606_F32_cam1_0452.png',
 'Canari/Endive_20251606_F32_cam2_2926.png',
 'Canari/Endive_20251606_F32_cam2_1699.png',
 'Canari/Endive_20251606_F32_cam1_0089.png',
 'Canari/Endive_20251606_F32_cam1_0499.png',
 'Canari/Endive_20251606_F32_cam1_2483.png',
 'Canari/Endive_20251606_F32_cam1_2326.png',
 'Canari/Endive_20251606_F32_cam2_0825.png',
 'Canari/Endive_20251606_F32_cam2_1008.png',
 'Canari/Endive_20251606_F32_cam2_1803.png',
 'Canari/Endive_20251606_F32_cam1_2802.png',
 'Canari/Endive_20251606_F32_cam1_2189.png',
 'Canari/Endive_20251606_F32_cam1_2734.png',
 'Canari/Endive_20251606_F32_cam1_1265.png',
 'Canari/Endive_20251606_F32_cam1_0529.png',
 'Canari/Endive_20251606_F32_cam1_0113.png',
 'Canari/Endive_20251606_F32_cam2_2408.png',
 'Canari/Endive_20251606_F32_cam2_2848.png',
 'Canari/Endive_20251606_F32_cam2_1987.png',
 'Canari/Endive_20251606_F32_cam2_2719.png',
 'Canari/Endive_20251606_F32_cam1_1103.png',
 'Canari/Endive_20251606_F32_cam2_2340.png',
 'Canari/Endive_20251606_F32_cam1_3474.png',
 'Canari/Endive_20251606_F32_cam1_3579.png',
 'Canari/Endive_20251606_F32_cam1_2811.png',
 'Canari/Endive_20251606_F32_cam2_1364.png',
 'Canari/Endive_20251606_F32_cam2_0416.png',
 'Canari/Endive_20251606_F32_cam2_0253.png',
 'Canari/Endive_20251606_F32_cam1_0037.png',
 'Canari/Endive_20251606_F32_cam2_1820.png',
 'Canari/Endive_20251606_F32_cam1_0930.png',
 'Canari/Endive_20251606_F32_cam2_2838.png',
 'Canari/Endive_20251606_F32_cam1_0273.png',
 'Canari/Endive_20251606_F32_cam2_1400.png',
 'Canari/Endive_20251606_F32_cam2_1652.png',
 'Canari/Endive_20251606_F32_cam2_2885.png',
 'Canari/Endive_20251606_F32_cam1_2354.png',
 'Canari/Endive_20251606_F32_cam2_0521.png',
 'Canari/Endive_20251606_F32_cam2_0665.png',
 'Canari/Endive_20251606_F32_cam2_0113.png',
 'Canari/Endive_20251606_F32_cam1_3200.png',
 'Canari/Endive_20251606_F32_cam1_3454.png',
 'Canari/Endive_20251606_F32_cam1_2469.png',
 'Canari/Endive_20251606_F32_cam2_2597.png',
 'Canari/Endive_20251606_F32_cam1_1401.png',
 'Canari/Endive_20251606_F32_cam2_0819.png',
 'Canari/Endive_20251606_F32_cam1_2554.png',
 'Canari/Endive_20251606_F32_cam2_1265.png',
 'Canari/Endive_20251606_F32_cam2_0822.png',
 'Canari/Endive_20251606_F32_cam2_3681.png',
 'Canari/Endive_20251606_F32_cam1_2455.png',
 'Canari/Endive_20251606_F32_cam1_1493.png',
 'Canari/Endive_20251606_F32_cam1_1364.png',
 'Canari/Endive_20251606_F32_cam2_3278.png',
 'Canari/Endive_20251606_F32_cam1_3665.png',
 'Canari/Endive_20251606_F32_cam2_0358.png',
 'Canari/Endive_20251606_F32_cam1_2161.png',
 'Canari/Endive_20251606_F32_cam1_1491.png',
 'Canari/Endive_20251606_F32_cam1_3020.png',
 'Canari/Endive_20251606_F32_cam2_2109.png',
 'Canari/Endive_20251606_F32_cam1_3478.png',
 'Canari/Endive_20251606_F32_cam2_1971.png',
 'Canari/Endive_20251606_F32_cam2_0646.png',
 'Canari/Endive_20251606_F32_cam2_1942.png',
 'Canari/Endive_20251606_F32_cam1_3176.png',
 'Canari/Endive_20251606_F32_cam1_1352.png',
 'Canari/Endive_20251606_F32_cam1_3126.png',
 'Canari/Endive_20251606_F32_cam1_3660.png',
 'Canari/Endive_20251606_F32_cam1_1608.png',
 'Canari/Endive_20251606_F32_cam2_2734.png',
 'Canari/Endive_20251606_F32_cam2_2659.png',
 'Canari/Endive_20251606_F32_cam2_1504.png',
 'Canari/Endive_20251606_F32_cam1_3112.png',
 'Canari/Endive_20251606_F32_cam1_0524.png',
 'Canari/Endive_20251606_F32_cam1_3387.png',
 'Canari/Endive_20251606_F32_cam2_0734.png',
 'Canari/Endive_20251606_F32_cam1_2839.png',
 'Canari/Endive_20251606_F32_cam2_1958.png',
 'Canari/Endive_20251606_F32_cam2_2587.png',
 'Canari/Endive_20251606_F32_cam2_2049.png',
 'Canari/Endive_20251606_F32_cam2_2509.png',
 'Canari/Endive_20251606_F32_cam2_2317.png',
 'Canari/Endive_20251606_F32_cam2_0668.png',
 'Canari/Endive_20251606_F32_cam1_2143.png',
 'Canari/Endive_20251606_F32_cam2_1462.png',
 'Canari/Endive_20251606_F32_cam2_0428.png',
 'Canari/Endive_20251606_F32_cam1_0343.png',
 'Canari/Endive_20251606_F32_cam1_1008.png',
 'Canari/Endive_20251606_F32_cam2_2988.png',
 'Canari/Endive_20251606_F32_cam1_3348.png',
 'Canari/Endive_20251606_F32_cam2_1526.png',
 'Canari/Endive_20251606_F32_cam2_3506.png',
 'Canari/Endive_20251606_F32_cam2_1585.png',
 'Canari/Endive_20251606_F32_cam2_2181.png',
 'Canari/Endive_20251606_F32_cam1_0774.png',
 'Canari/Endive_20251606_F32_cam1_0889.png',
 'Canari/Endive_20251606_F32_cam1_3423.png',
 'Canari/Endive_20251606_F32_cam1_3311.png',
 'Canari/Endive_20251606_F32_cam1_2908.png',
 'Canari/Endive_20251606_F32_cam2_0546.png',
 'Canari/Endive_20251606_F32_cam2_0456.png',
 'Canari/Endive_20251606_F32_cam2_1037.png',
 'Canari/Endive_20251606_F32_cam1_3328.png',
 'Canari/Endive_20251606_F32_cam2_3579.png',
 'Canari/Endive_20251606_F32_cam1_2625.png',
 'Canari/Endive_20251606_F32_cam1_2722.png',
 'Canari/Endive_20251606_F32_cam2_1912.png',
 'Canari/Endive_20251606_F32_cam2_2850.png',
 'Canari/Endive_20251606_F32_cam1_1152.png',
 'Canari/Endive_20251606_F32_cam1_1652.png',
 'Canari/Endive_20251606_F32_cam1_1460.png',
 'Canari/Endive_20251606_F32_cam1_3169.png',
 'Canari/Endive_20251606_F32_cam1_0092.png',
 'Canari/Endive_20251606_F32_cam1_3142.png',
 'Canari/Endive_20251606_F32_cam2_0013.png',
 'Canari/Endive_20251606_F32_cam1_3188.png',
 'Canari/Endive_20251606_F32_cam2_2077.png',
 'Canari/Endive_20251606_F32_cam2_0001.png',
 'Canari/Endive_20251606_F32_cam1_0703.png',
 'Canari/Endive_20251606_F32_cam1_2551.png',
 'Canari/Endive_20251606_F32_cam2_2683.png',
 'Canari/Endive_20251606_F32_cam1_2583.png',
 'Canari/Endive_20251606_F32_cam2_3053.png',
 'Canari/Endive_20251606_F32_cam2_1603.png',
 'Canari/Endive_20251606_F32_cam1_1191.png',
 'Canari/Endive_20251606_F32_cam2_2574.png',
 'Canari/Endive_20251606_F32_cam1_1437.png',
 'Canari/Endive_20251606_F32_cam2_3532.png',
 'Canari/Endive_20251606_F32_cam1_1037.png',
 'Canari/Endive_20251606_F32_cam2_2908.png',
 'Canari/Endive_20251606_F32_cam1_0393.png',
 'Canari/Endive_20251606_F32_cam1_0719.png',
 'Canari/Endive_20251606_F32_cam2_0205.png',
 'Canari/Endive_20251606_F32_cam1_1253.png',
 'Canari/Endive_20251606_F32_cam2_1964.png',
 'Canari/Endive_20251606_F32_cam1_1620.png',
 'Canari/Endive_20251606_F32_cam2_0362.png',
 'Canari/Endive_20251606_F32_cam2_1547.png',
 'Canari/Endive_20251606_F32_cam2_3018.png',
 'Canari/Endive_20251606_F32_cam2_1150.png',
 'Canari/Endive_20251606_F32_cam2_1305.png',
 'Canari/Endive_20251606_F32_cam1_1007.png',
 'Canari/Endive_20251606_F32_cam2_0499.png',
 'Canari/Endive_20251606_F32_cam2_2624.png',
 'Canari/Endive_20251606_F32_cam2_0479.png',
 'Canari/Endive_20251606_F32_cam2_3099.png',
 'Canari/Endive_20251606_F32_cam1_3545.png',
 'Canari/Endive_20251606_F32_cam2_3129.png',
 'Canari/Endive_20251606_F32_cam2_2790.png',
 'Canari/Endive_20251606_F32_cam1_0596.png',
 'Canari/Endive_20251606_F32_cam2_0500.png',
 'Canari/Endive_20251606_F32_cam2_0616.png',
 'Canari/Endive_20251606_F32_cam2_3004.png',
 'Canari/Endive_20251606_F32_cam2_3641.png',
 'Canari/Endive_20251606_F32_cam1_0724.png',
 'Canari/Endive_20251606_F32_cam2_0875.png',
 'Canari/Endive_20251606_F32_cam2_2866.png',
 'Canari/Endive_20251606_F32_cam2_2363.png',
 'Canari/Endive_20251606_F32_cam1_0840.png',
 'Canari/Endive_20251606_F32_cam2_1274.png',
 'Canari/Endive_20251606_F32_cam2_2314.png',
 'Canari/Endive_20251606_F32_cam1_3480.png',
 'Canari/Endive_20251606_F32_cam2_0731.png',
 'Canari/Endive_20251606_F32_cam1_0248.png',
 'Canari/Endive_20251606_F32_cam1_3635.png',
 'Canari/Endive_20251606_F32_cam2_3621.png',
 'Canari/Endive_20251606_F32_cam1_1429.png',
 'Canari/Endive_20251606_F32_cam1_3350.png',
 'Canari/Endive_20251606_F32_cam1_0341.png',
 'Canari/Endive_20251606_F32_cam1_0810.png',
 'Canari/Endive_20251606_F32_cam2_0541.png',
 'Canari/Endive_20251606_F32_cam2_3235.png',
 'Canari/Endive_20251606_F32_cam2_1370.png',
 'Canari/Endive_20251606_F32_cam2_0639.png',
 'Canari/Endive_20251606_F32_cam1_0267.png',
 'Canari/Endive_20251606_F32_cam1_2539.png',
 'Canari/Endive_20251606_F32_cam1_2021.png',
 'Canari/Endive_20251606_F32_cam1_0096.png',
 'Canari/Endive_20251606_F32_cam1_0665.png',
 'Canari/Endive_20251606_F32_cam2_1651.png',
 'Canari/Endive_20251606_F32_cam2_2625.png',
 'Canari/Endive_20251606_F32_cam1_2152.png',
 'Canari/Endive_20251606_F32_cam1_2216.png',
 'Canari/Endive_20251606_F32_cam1_3254.png',
 'Canari/Endive_20251606_F32_cam2_0776.png',
 'Canari/Endive_20251606_F32_cam1_3239.png',
 'Canari/Endive_20251606_F32_cam1_2363.png',
 'Canari/Endive_20251606_F32_cam1_0043.png',
 'Canari/Endive_20251606_F32_cam2_0082.png',
 'Canari/Endive_20251606_F32_cam2_1126.png',
 'Canari/Endive_20251606_F32_cam1_2675.png',
 'Canari/Endive_20251606_F32_cam1_3339.png',
 'Canari/Endive_20251606_F32_cam2_2745.png',
 'Canari/Endive_20251606_F32_cam2_3204.png',
 'Canari/Endive_20251606_F32_cam2_2984.png',
 'Canari/Endive_20251606_F32_cam1_2605.png',
 'Canari/Endive_20251606_F32_cam2_2110.png',
 'Canari/Endive_20251606_F32_cam1_3281.png',
 'Canari/Endive_20251606_F32_cam1_1691.png',
 'Canari/Endive_20251606_F32_cam1_0639.png',
 'Canari/Endive_20251606_F32_cam1_2423.png',
 'Canari/Endive_20251606_F32_cam1_3532.png',
 'Canari/Endive_20251606_F32_cam1_2135.png',
 'Canari/Endive_20251606_F32_cam1_2178.png',
 'Canari/Endive_20251606_F32_cam1_2984.png',
 'Canari/Endive_20251606_F32_cam2_3007.png',
 'Canari/Endive_20251606_F32_cam2_3218.png',
 'Canari/Endive_20251606_F32_cam2_1112.png',
 'Canari/Endive_20251606_F32_cam2_2129.png',
 'Canari/Endive_20251606_F32_cam2_3329.png',
 'Canari/Endive_20251606_F32_cam2_2165.png',
 'Canari/Endive_20251606_F32_cam1_2351.png',
 'Canari/Endive_20251606_F32_cam1_1681.png',
 'Canari/Endive_20251606_F32_cam1_3053.png',
 'Canari/Endive_20251606_F32_cam2_0267.png',
 'Canari/Endive_20251606_F32_cam2_0388.png',
 'Canari/Endive_20251606_F32_cam1_2567.png',
 'Canari/Endive_20251606_F32_cam1_2125.png',
 'Canari/Endive_20251606_F32_cam1_1545.png',
 'Canari/Endive_20251606_F32_cam1_1099.png',
 'Canari/Endive_20251606_F32_cam2_0141.png',
 'Canari/Endive_20251606_F32_cam2_0851.png',
 'Canari/Endive_20251606_F32_cam1_2876.png',
 'Canari/Endive_20251606_F32_cam1_0843.png',
 'Canari/Endive_20251606_F32_cam1_1290.png',
 'Canari/Endive_20251606_F32_cam1_2868.png',
 'Canari/Endive_20251606_F32_cam2_0598.png',
 'Canari/Endive_20251606_F32_cam2_3056.png',
 'Canari/Endive_20251606_F32_cam1_2659.png',
 'Canari/Endive_20251606_F32_cam1_0073.png',
 'Canari/Endive_20251606_F32_cam2_0552.png',
 'Canari/Endive_20251606_F32_cam2_1164.png',
 'Canari/Endive_20251606_F32_cam1_0804.png',
 'Canari/Endive_20251606_F32_cam2_3677.png',
 'Canari/Endive_20251606_F32_cam2_3050.png',
 'Canari/Endive_20251606_F32_cam2_2656.png',
 'Canari/Endive_20251606_F32_cam2_1604.png',
 'Canari/Endive_20251606_F32_cam2_2516.png',
 'Canari/Endive_20251606_F32_cam1_0142.png',
 'Canari/Endive_20251606_F32_cam1_3529.png',
 'Canari/Endive_20251606_F32_cam1_1544.png',
 'Canari/Endive_20251606_F32_cam1_0532.png',
 'Canari/Endive_20251606_F32_cam1_1038.png',
 'Canari/Endive_20251606_F32_cam2_2675.png',
 'Canari/Endive_20251606_F32_cam1_1779.png',
 'Canari/Endive_20251606_F32_cam1_1453.png',
 'Canari/Endive_20251606_F32_cam2_0685.png',
 'Canari/Endive_20251606_F32_cam1_0819.png',
 'Canari/Endive_20251606_F32_cam2_1488.png',
 'Canari/Endive_20251606_F32_cam1_0321.png',
 'Canari/Endive_20251606_F32_cam2_1545.png',
 'Canari/Endive_20251606_F32_cam1_0598.png',
 'Canari/Endive_20251606_F32_cam2_0365.png',
 'Canari/Endive_20251606_F32_cam1_1685.png',
 'Canari/Endive_20251606_F32_cam1_0367.png',
 'Canari/Endive_20251606_F32_cam2_3115.png',
 'Canari/Endive_20251606_F32_cam1_0115.png',
 'Canari/Endive_20251606_F32_cam2_3529.png',
 'Canari/Endive_20251606_F32_cam2_3238.png',
 'Canari/Endive_20251606_F32_cam1_0944.png',
 'Canari/Endive_20251606_F32_cam1_3158.png',
 'Canari/Endive_20251606_F32_cam1_1257.png',
 'Canari/Endive_20251606_F32_cam2_2607.png',
 'Canari/Endive_20251606_F32_cam1_2558.png',
 'Canari/Endive_20251606_F32_cam2_1152.png',
 'Canari/Endive_20251606_F32_cam1_1970.png',
 'Canari/Endive_20251606_F32_cam1_0202.png',
 'Canari/Endive_20251606_F32_cam1_1942.png',
 'Canari/Endive_20251606_F32_cam2_1708.png',
 'Canari/Endive_20251606_F32_cam1_2193.png',
 'Canari/Endive_20251606_F32_cam1_1123.png',
 'Canari/Endive_20251606_F32_cam2_1535.png',
 'Canari/Endive_20251606_F32_cam2_1933.png',
 'Canari/Endive_20251606_F32_cam2_2857.png',
 'Canari/Endive_20251606_F32_cam1_0191.png',
 'Canari/Endive_20251606_F32_cam2_1544.png',
 'Canari/Endive_20251606_F32_cam1_3382.png',
 'Canari/Endive_20251606_F32_cam1_0364.png',
 'Canari/Endive_20251606_F32_cam1_1645.png',
 'Canari/Endive_20251606_F32_cam1_3641.png',
 'Canari/Endive_20251606_F32_cam1_0917.png',
 'Canari/Endive_20251606_F32_cam1_2127.png',
 'Canari/Endive_20251606_F32_cam2_0068.png',
 'Canari/Endive_20251606_F32_cam2_0021.png',
 'Canari/Endive_20251606_F32_cam2_1381.png',
 'Canari/Endive_20251606_F32_cam2_3304.png',
 'Canari/Endive_20251606_F32_cam1_0711.png',
 'Canari/Endive_20251606_F32_cam1_1566.png',
 'Canari/Endive_20251606_F32_cam2_1497.png',
 'Canari/Endive_20251606_F32_cam1_0411.png',
 'Canari/Endive_20251606_F32_cam1_0566.png',
 'Canari/Endive_20251606_F32_cam2_0529.png',
 'Canari/Endive_20251606_F32_cam2_1407.png',
 'Canari/Endive_20251606_F32_cam1_3595.png',
 'Canari/Endive_20251606_F32_cam1_1971.png',
 'Canari/Endive_20251606_F32_cam2_2630.png',
 'Canari/Endive_20251606_F32_cam1_2240.png',
 'Canari/Endive_20251606_F32_cam2_0020.png',
 'Canari/Endive_20251606_F32_cam2_1005.png',

## 7. Training — ResNet50 vs HRNet

Iterates over all **12 combinations** (2 architectures × 3 frame counts × 2 birds).  
Architecture is hot-swapped by patching `net_type` in each project's `config.yaml` before calling `create_training_dataset`.  
Wall-clock training time is recorded per run for comparison.

In [11]:

def set_net_type(config_path: Path, net_type: str) -> None:
    """Patch the net_type field in a DLC config.yaml in-place."""
    config_path = Path(config_path)
    with open(config_path, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)
    cfg["default_net_type"] = net_type
    with open(config_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(cfg, fh, sort_keys=False)

RUN_TRAINING      = True
USE_FULL_EPOCHS   = True
epochs = EPOCHS_FULL if USE_FULL_EPOCHS else EPOCHS_SMOKE
training_results = []  # list of dicts — one entry per (bird, n, arch) run

if not RUN_TRAINING:
    print("DRY RUN — set RUN_TRAINING = True to execute training.")
    for bird_name in BIRDS:
        for n in FRAME_COUNTS:
            for arch in ARCHITECTURES:
                training_results.append({
                    "bird": bird_name, "nframes": n, "architecture": arch,
                    "epochs": epochs, "trained": False,
                    "train_time_s": None, "latest_snapshot": None,
                    "notes": "dry run",
                })
else:
    for bird_name in BIRDS:
        for n in FRAME_COUNTS:
            train_cfg = combined_configs[(bird_name, n)]
            for arch in ARCHITECTURES:
                run_label = f"{bird_name} | n={n} | {arch}"
                print(f"\n{'─'*60}")
                print(f"Training: {run_label}")

                # Switch architecture in config.yaml
                set_net_type(train_cfg, arch)

                # Time the full create_training_dataset + train_network cycle
                t0 = time.perf_counter()
                try:
                    latest_snap = dlcs.create_and_train(
                        config_path   = train_cfg,
                        epochs        = epochs,
                        snapshot_path = None,   # always start fresh per variant
                    )
                    elapsed = time.perf_counter() - t0
                    training_results.append({
                        "bird": bird_name, "nframes": n, "architecture": arch,
                        "epochs": epochs, "trained": True,
                        "train_time_s": round(elapsed, 1),
                        "latest_snapshot": latest_snap,
                        "notes": "",
                    })
                    print(f"  Done in {elapsed/60:.1f} min  ->  {latest_snap}")
                except Exception as exc:
                    elapsed = time.perf_counter() - t0
                    training_results.append({
                        "bird": bird_name, "nframes": n, "architecture": arch,
                        "epochs": epochs, "trained": False,
                        "train_time_s": round(elapsed, 1),
                        "latest_snapshot": None,
                        "notes": str(exc),
                    })
                    print(f"  ERROR: {exc}")

print(f"\n{'─'*60}")
print(f"Training runs recorded: {len(training_results)}")
pd.DataFrame(training_results)[["bird", "nframes", "architecture", "trained", "train_time_s"]]

INFO | Default augmenter albumentations not available for engine Engine.PYTORCH: using albumentations instead

────────────────────────────────────────────────────────────
Training: DavidBowie | n=200 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n200\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n200\\Canari-Tyler-2026-04-08\\labeled-data\\DB17_cam1']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Cranium_Left_Anterior', 'Cranium_Left_Middle', 'Cranium_Right_Middle', 'Cranium_Right_Posterior', 'Beak_Mandible_Left_Posterior', 'Beak_Mandibile_Left_Anterior', 'Beak_Mandible_Right_Anterior', 'Beak_Maxilla_Right_Anterior', 'Beak_Maxilla_Right_Posterior', 'Beak_Maxilla_Left_Anterior', 'Beak_Maxilla_Left_Posterior', 'Tongue_Lower_Palette', 'Glottis', 'Superior_Trachea', 'Keel_Dorsal_Anterior', 'Keel_Dorsal_Posterior', 'Keel_Inferior', 'Pelvis_Right_Inferior', 'Pelvis_Right_Superior', 'Pelvis_Left_Superior', 'Pelvis_Left_Inferior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 21
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 21]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 42]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 380 images and 20 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00851, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00274, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00189, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00149, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00129, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00111, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00097, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00088, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00087, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00075, valid loss 0.00071, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.87
  metrics/test.rmse_pcutoff:   1.86
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00073, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00067, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00065, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00074, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00059, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00055, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00052, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00050, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00048, valid loss 0.00045, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.60
  metrics/test.rmse_pcutoff:   1.60
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00051, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00051, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00047, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00047, valid loss 0.00026, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.12
  metrics/test.rmse_pcutoff:   1.12
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00041, valid loss 0.00035, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.41
  metrics/test.rmse_pcutoff:   1.41
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00039, valid loss 0.00026, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.17
  metrics/test.rmse_pcutoff:   1.17
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00035, valid loss 0.00028, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.26
  metrics/test.rmse_pcutoff:   1.26
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00034, valid loss 0.00017, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.97
  metrics/test.rmse_pcutoff:   0.97
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00031, valid loss 0.00025, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.21
  metrics/test.rmse_pcutoff:   1.21
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00025, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.85
  metrics/test.rmse_pcutoff:   0.85
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00025, valid loss 0.00009, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.67
  metrics/test.rmse_pcutoff:   0.67
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00021, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.70
  metrics/test.rmse_pcutoff:   0.70
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00020, valid loss 0.00009, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.68
  metrics/test.rmse_pcutoff:   0.68
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00020, valid loss 0.00007, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.60
  metrics/test.rmse_pcutoff:   0.60
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00019, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.62
  metrics/test.rmse_pcutoff:   0.62
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00018, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.65
  metrics/test.rmse_pcutoff:   0.65
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: DavidBowie | n=400 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n400\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n400\\Canari-Tyler-2026-04-08\\labeled-data\\DB17_cam1']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Cranium_Left_Anterior', 'Cranium_Left_Middle', 'Cranium_Right_Middle', 'Cranium_Right_Posterior', 'Beak_Mandible_Left_Posterior', 'Beak_Mandibile_Left_Anterior', 'Beak_Mandible_Right_Anterior', 'Beak_Maxilla_Right_Anterior', 'Beak_Maxilla_Right_Posterior', 'Beak_Maxilla_Left_Anterior', 'Beak_Maxilla_Left_Posterior', 'Tongue_Lower_Palette', 'Glottis', 'Superior_Trachea', 'Keel_Dorsal_Anterior', 'Keel_Dorsal_Posterior', 'Keel_Inferior', 'Pelvis_Right_Inferior', 'Pelvis_Right_Superior', 'Pelvis_Left_Superior', 'Pelvis_Left_Inferior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 21
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 21]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 42]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 760 images and 40 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00601, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00163, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00111, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00093, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00080, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00066, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00065, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00056, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00057, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00050, valid loss 0.00041, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.51
  metrics/test.rmse_pcutoff:   1.51
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00052, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00051, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00038, valid loss 0.00025, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.19
  metrics/test.rmse_pcutoff:   1.19
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00034, valid loss 0.00025, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.12
  metrics/test.rmse_pcutoff:   1.12
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00029, valid loss 0.00021, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.97
  metrics/test.rmse_pcutoff:   0.97
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00034, valid loss 0.00022, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.08
  metrics/test.rmse_pcutoff:   1.08
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00047, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00031, valid loss 0.00017, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.97
  metrics/test.rmse_pcutoff:   0.97
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00027, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.81
  metrics/test.rmse_pcutoff:   0.81
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00029, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.81
  metrics/test.rmse_pcutoff:   0.81
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00029, valid loss 0.00020, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.09
  metrics/test.rmse_pcutoff:   1.09
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00020, valid loss 0.00006, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.59
  metrics/test.rmse_pcutoff:   0.59
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00021, valid loss 0.00006, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.58
  metrics/test.rmse_pcutoff:   0.58
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00019, valid loss 0.00007, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.59
  metrics/test.rmse_pcutoff:   0.59
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00017, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.52
  metrics/test.rmse_pcutoff:   0.52
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00020, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.53
  metrics/test.rmse_pcutoff:   0.53
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00018, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.52
  metrics/test.rmse_pcutoff:   0.52
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 158/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 159/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 160 done, starting evaluation

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: DavidBowie | n=800 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n800\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n800\\Canari-Tyler-2026-04-08\\labeled-data\\DB17_cam1']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Cranium_Left_Anterior', 'Cranium_Left_Middle', 'Cranium_Right_Middle', 'Cranium_Right_Posterior', 'Beak_Mandible_Left_Posterior', 'Beak_Mandibile_Left_Anterior', 'Beak_Mandible_Right_Anterior', 'Beak_Maxilla_Right_Anterior', 'Beak_Maxilla_Right_Posterior', 'Beak_Maxilla_Left_Anterior', 'Beak_Maxilla_Left_Posterior', 'Tongue_Lower_Palette', 'Glottis', 'Superior_Trachea', 'Keel_Dorsal_Anterior', 'Keel_Dorsal_Posterior', 'Keel_Inferior', 'Pelvis_Right_Inferior', 'Pelvis_Right_Superior', 'Pelvis_Left_Superior', 'Pelvis_Left_Inferior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 21
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 21]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 42]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 1520 images and 80 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00383, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00105, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00073, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00049, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00042, valid loss 0.00017, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.96
  metrics/test.rmse_pcutoff:   0.96
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00032, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.79
  metrics/test.rmse_pcutoff:   0.79
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00031, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.77
  metrics/test.rmse_pcutoff:   0.77
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00031, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.71
  metrics/test.rmse_pcutoff:   0.71
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00027, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.84
  metrics/test.rmse_pcutoff:   0.84
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00026, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.72
  metrics/test.rmse_pcutoff:   0.72
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00025, valid loss 0.00012, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.82
  metrics/test.rmse_pcutoff:   0.82
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00024, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.63
  metrics/test.rmse_pcutoff:   0.63
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00024, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.65
  metrics/test.rmse_pcutoff:   0.65
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00016, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.51
  metrics/test.rmse_pcutoff:   0.51
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00018, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.50
  metrics/test.rmse_pcutoff:   0.50
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00017, valid loss 0.00005, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.51
  metrics/test.rmse_pcutoff:   0.51
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00015, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.48
  metrics/test.rmse_pcutoff:   0.48
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00014, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.46
  metrics/test.rmse_pcutoff:   0.46
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00015, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.47
  metrics/test.rmse_pcutoff:   0.47
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 158/200 (lr=1e-05), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 159/200 (lr=1e-05), train loss 0.00015, GPU: 4016.0/8187.5 MiB
Training for epoch 160 done, starting evaluation

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: DavidBowie | n=1400 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n1400\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\DavidBowie\\TestData\\Canari_combined_n1400\\Canari-Tyler-2026-04-08\\labeled-data\\DB17_cam1']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data\DB17_cam1\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Cranium_Left_Anterior', 'Cranium_Left_Middle', 'Cranium_Right_Middle', 'Cranium_Right_Posterior', 'Beak_Mandible_Left_Posterior', 'Beak_Mandibile_Left_Anterior', 'Beak_Mandible_Right_Anterior', 'Beak_Maxilla_Right_Anterior', 'Beak_Maxilla_Right_Posterior', 'Beak_Maxilla_Left_Anterior', 'Beak_Maxilla_Left_Posterior', 'Tongue_Lower_Palette', 'Glottis', 'Superior_Trachea', 'Keel_Dorsal_Anterior', 'Keel_Dorsal_Posterior', 'Keel_Inferior', 'Pelvis_Right_Inferior', 'Pelvis_Right_Superior', 'Pelvis_Left_Superior', 'Pelvis_Left_Inferior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 21
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 21]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 42]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 2660 images and 140 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00249, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00071, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00053, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00035, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.83
  metrics/test.rmse_pcutoff:   0.83
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00028, valid loss 0.00012, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.79
  metrics/test.rmse_pcutoff:   0.79
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00025, valid loss 0.00021, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.12
  metrics/test.rmse_pcutoff:   1.12
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00025, valid loss 0.00014, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.93
  metrics/test.rmse_pcutoff:   0.93
  metrics/test.mAP:           99.85
  metrics/test.mAR:           99.93
Epoch 41/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00022, valid loss 0.00011, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.80
  metrics/test.rmse_pcutoff:   0.80
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00021, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.89
  metrics/test.rmse_pcutoff:   0.89
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00017, valid loss 0.00006, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.58
  metrics/test.rmse_pcutoff:   0.58
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00017, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.65
  metrics/test.rmse_pcutoff:   0.65
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00016, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.65
  metrics/test.rmse_pcutoff:   0.65
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00013, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.46
  metrics/test.rmse_pcutoff:   0.46
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00012, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.45
  metrics/test.rmse_pcutoff:   0.45
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00013, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.45
  metrics/test.rmse_pcutoff:   0.45
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00011, valid loss 0.00003, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.42
  metrics/test.rmse_pcutoff:   0.42
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00011, valid loss 0.00004, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.44
  metrics/test.rmse_pcutoff:   0.44
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00011, valid loss 0.00003, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.44
  metrics/test.rmse_pcutoff:   0.44
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 158/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 159/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\DavidBowie\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: Endive | n=200 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n200\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n200\\Canari-Tyler-2026-04-08\\labeled-data\\EndiveF42_20251606_Cam1_short']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Tongue_Marker', 'Glottis_Marker', 'Cranium_Marker_Anterior', 'Cranium_Marker_Middle_Left', 'Cranium_Marker_Posterior', 'Cranium_Marker_Middle_Right', 'Maxilla_Marker_Left_Posterior', 'Maxilla_Marker_Left_Anterior', 'Maxilla_Marker_Right_Posterior', 'Mandible_Marker_Right', 'Mandible_Marker_Left_Anterior', 'Mandible_Marker_Left_Posterior', 'Neck_Marker_Right_Superior', 'Neck_Marker_Left_Superior', 'Neck_Marker_Left_Inferior', 'Neck_Marker_Right_Inferior', 'Keel_Marker_Left_Superior', 'Keel_Marker_Left_Inferior', 'Keel_Marker_Right_Superior', 'Keel_Marker_Right_Inferior', 'Pelvis_Marker_Left', 'Pelvis_Marker_Right_Superior', 'Pelvis_Marker_Right_Inferior', 'Maxilla_Marker_Right_Anterior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 24
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 24]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 48]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 380 images and 20 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.01040, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00403, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00270, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00213, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00178, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00158, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00136, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00129, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00125, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00116, valid loss 0.00096, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           2.38
  metrics/test.rmse_pcutoff:   2.25
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00095, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00101, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00084, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00098, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00089, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00078, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00090, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00078, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00066, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00070, valid loss 0.00074, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           2.08
  metrics/test.rmse_pcutoff:   2.08
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00077, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00066, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00062, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00067, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00062, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00061, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00062, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00063, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00063, valid loss 0.00037, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.39
  metrics/test.rmse_pcutoff:   1.39
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00062, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00059, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00059, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00050, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00055, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00052, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00053, valid loss 0.00048, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.69
  metrics/test.rmse_pcutoff:   1.69
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00057, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00050, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00053, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00050, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00055, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00048, valid loss 0.00038, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.44
  metrics/test.rmse_pcutoff:   1.44
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00047, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00044, valid loss 0.00037, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.44
  metrics/test.rmse_pcutoff:   1.44
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00049, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00042, valid loss 0.00030, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.28
  metrics/test.rmse_pcutoff:   1.28
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00047, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00078, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00052, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00047, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00043, valid loss 0.00031, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.22
  metrics/test.rmse_pcutoff:   1.22
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00032, valid loss 0.00023, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.12
  metrics/test.rmse_pcutoff:   1.12
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00030, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.90
  metrics/test.rmse_pcutoff:   0.90
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00026, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.89
  metrics/test.rmse_pcutoff:   0.89
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00024, valid loss 0.00016, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.95
  metrics/test.rmse_pcutoff:   0.95
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00024, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.82
  metrics/test.rmse_pcutoff:   0.82
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00023, valid loss 0.00012, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.79
  metrics/test.rmse_pcutoff:   0.79
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00021, valid loss 0.00012, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.80
  metrics/test.rmse_pcutoff:   0.80
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00023, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n200\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: Endive | n=400 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n400\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n400\\Canari-Tyler-2026-04-08\\labeled-data\\EndiveF42_20251606_Cam1_short']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Tongue_Marker', 'Glottis_Marker', 'Cranium_Marker_Anterior', 'Cranium_Marker_Middle_Left', 'Cranium_Marker_Posterior', 'Cranium_Marker_Middle_Right', 'Maxilla_Marker_Left_Posterior', 'Maxilla_Marker_Left_Anterior', 'Maxilla_Marker_Right_Posterior', 'Mandible_Marker_Right', 'Mandible_Marker_Left_Anterior', 'Mandible_Marker_Left_Posterior', 'Neck_Marker_Right_Superior', 'Neck_Marker_Left_Superior', 'Neck_Marker_Left_Inferior', 'Neck_Marker_Right_Inferior', 'Keel_Marker_Left_Superior', 'Keel_Marker_Left_Inferior', 'Keel_Marker_Right_Superior', 'Keel_Marker_Right_Inferior', 'Pelvis_Marker_Left', 'Pelvis_Marker_Right_Superior', 'Pelvis_Marker_Right_Inferior', 'Maxilla_Marker_Right_Anterior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 24
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 24]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 48]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 760 images and 40 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00672, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00216, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00165, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00129, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00118, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00099, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00089, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00079, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00078, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00068, valid loss 0.00068, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.86
  metrics/test.rmse_pcutoff:   1.71
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00064, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00065, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00064, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00058, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00057, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00058, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00057, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00050, valid loss 0.00051, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.70
  metrics/test.rmse_pcutoff:   1.59
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00055, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00053, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00051, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00048, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00042, valid loss 0.00041, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.44
  metrics/test.rmse_pcutoff:   1.42
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00037, valid loss 0.00032, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.17
  metrics/test.rmse_pcutoff:   1.08
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00052, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00056, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00042, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00043, valid loss 0.00028, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.09
  metrics/test.rmse_pcutoff:   1.08
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00037, valid loss 0.00032, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.22
  metrics/test.rmse_pcutoff:   1.22
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00033, valid loss 0.00034, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.22
  metrics/test.rmse_pcutoff:   1.05
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00031, valid loss 0.00026, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.11
  metrics/test.rmse_pcutoff:   1.11
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00034, valid loss 0.00027, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.21
  metrics/test.rmse_pcutoff:   1.21
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00025, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.81
  metrics/test.rmse_pcutoff:   0.81
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00023, valid loss 0.00016, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.83
  metrics/test.rmse_pcutoff:   0.83
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00022, valid loss 0.00016, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.79
  metrics/test.rmse_pcutoff:   0.79
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00020, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.75
  metrics/test.rmse_pcutoff:   0.74
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00022, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.75
  metrics/test.rmse_pcutoff:   0.75
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00020, valid loss 0.00015, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.73
  metrics/test.rmse_pcutoff:   0.73
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: Endive | n=800 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n800\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n800\\Canari-Tyler-2026-04-08\\labeled-data\\EndiveF42_20251606_Cam1_short']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Tongue_Marker', 'Glottis_Marker', 'Cranium_Marker_Anterior', 'Cranium_Marker_Middle_Left', 'Cranium_Marker_Posterior', 'Cranium_Marker_Middle_Right', 'Maxilla_Marker_Left_Posterior', 'Maxilla_Marker_Left_Anterior', 'Maxilla_Marker_Right_Posterior', 'Mandible_Marker_Right', 'Mandible_Marker_Left_Anterior', 'Mandible_Marker_Left_Posterior', 'Neck_Marker_Right_Superior', 'Neck_Marker_Left_Superior', 'Neck_Marker_Left_Inferior', 'Neck_Marker_Right_Inferior', 'Keel_Marker_Left_Superior', 'Keel_Marker_Left_Inferior', 'Keel_Marker_Right_Superior', 'Keel_Marker_Right_Inferior', 'Pelvis_Marker_Left', 'Pelvis_Marker_Right_Superior', 'Pelvis_Marker_Right_Inferior', 'Maxilla_Marker_Right_Anterior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 24
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 24]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 48]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 1520 images and 80 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00449, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00151, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00111, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00089, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00078, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00071, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00065, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00057, valid loss 0.00053, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.73
  metrics/test.rmse_pcutoff:   1.71
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00054, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00050, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00066, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00049, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00045, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00041, valid loss 0.00024, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.12
  metrics/test.rmse_pcutoff:   1.12
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00045, valid loss 0.00023, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.13
  metrics/test.rmse_pcutoff:   1.13
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00034, valid loss 0.00019, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.00
  metrics/test.rmse_pcutoff:   0.99
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00035, valid loss 0.00022, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.03
  metrics/test.rmse_pcutoff:   1.02
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00032, valid loss 0.00017, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.92
  metrics/test.rmse_pcutoff:   0.91
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00031, valid loss 0.00019, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.95
  metrics/test.rmse_pcutoff:   0.95
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00029, valid loss 0.00018, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.94
  metrics/test.rmse_pcutoff:   0.94
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00029, valid loss 0.00014, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.83
  metrics/test.rmse_pcutoff:   0.83
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00020, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.70
  metrics/test.rmse_pcutoff:   0.70
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00020, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.71
  metrics/test.rmse_pcutoff:   0.71
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00019, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.71
  metrics/test.rmse_pcutoff:   0.71
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00017, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.67
  metrics/test.rmse_pcutoff:   0.67
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00016, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.69
  metrics/test.rmse_pcutoff:   0.69
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00019, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00018, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.70
  metrics/test.rmse_pcutoff:   0.70
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00018, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00017, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n800\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training: Endive | n=1400 | resnet_50
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n1400\\Canari-Tyler-2026-04-08\\labeled-data\\Canari', 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\DeepLabCut\\Endive\\TestData\\Canari_combined_n1400\\Canari-Tyler-2026-04-08\\labeled-data\\EndiveF42_20251606_Cam1_short']
C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\labeled-data\EndiveF42_20251606_Cam1_short\CollectedData_Tyler.h5  not found (perhaps not annotated)

Training with configuration:
data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [0.5, 1.25]
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: True
    normalize_images: True
device: auto
inference:
  multithreading:
    enabled: True
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: False
    backend: inductor
  autocast:
    enabled: False
metadata:
  project_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08
  pose_config_path: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\CanariApr8-trainset95shuffle1\train\pytorch_config.yaml
  bodyparts: ['Tongue_Marker', 'Glottis_Marker', 'Cranium_Marker_Anterior', 'Cranium_Marker_Middle_Left', 'Cranium_Marker_Posterior', 'Cranium_Marker_Middle_Right', 'Maxilla_Marker_Left_Posterior', 'Maxilla_Marker_Left_Anterior', 'Maxilla_Marker_Right_Posterior', 'Mandible_Marker_Right', 'Mandible_Marker_Left_Anterior', 'Mandible_Marker_Left_Posterior', 'Neck_Marker_Right_Superior', 'Neck_Marker_Left_Superior', 'Neck_Marker_Left_Inferior', 'Neck_Marker_Right_Inferior', 'Keel_Marker_Left_Superior', 'Keel_Marker_Left_Inferior', 'Keel_Marker_Right_Superior', 'Keel_Marker_Right_Inferior', 'Pelvis_Marker_Left', 'Pelvis_Marker_Right_Superior', 'Pelvis_Marker_Right_Inferior', 'Maxilla_Marker_Right_Anterior']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: False
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 24
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 24]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 48]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[0.0001], [1e-05]]
      milestones: [90, 120]
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: False
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 500
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
HTTP Request: HEAD https://huggingface.co/timm/resnet50_gn.a1h_in1k/resolve/main/model.safetensors "HTTP/1.1 302 Found"
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (0.5, 1.25), 'y': (0.5, 1.25)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  PadIfNeeded(always_apply=True, p=1.0, min_height=448, min_width=448, pad_height_divisor=None, pad_width_divisor=None, position=PositionType.CENTER, border_mode=0, value=None, mask_value=None),
  KeypointAwareCrop(always_apply=True, p=1.0, width=448, height=448, max_shift=0.1, crop_sampling='hybrid'),
  MotionBlur(always_apply=False, p=0.5, blur_limit=(3, 7), allow_shifted=True),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using 2660 images and 140 for testing

Starting pose model training...
--------------------------------------------------
Epoch 1/200 (lr=0.0005), train loss 0.00331, GPU: 4016.0/8187.5 MiB
Epoch 2/200 (lr=0.0005), train loss 0.00108, GPU: 4016.0/8187.5 MiB
Epoch 3/200 (lr=0.0005), train loss 0.00079, GPU: 4016.0/8187.5 MiB
Epoch 4/200 (lr=0.0005), train loss 0.00064, GPU: 4016.0/8187.5 MiB
Epoch 5/200 (lr=0.0005), train loss 0.00060, GPU: 4016.0/8187.5 MiB
Epoch 6/200 (lr=0.0005), train loss 0.00057, GPU: 4016.0/8187.5 MiB
Epoch 7/200 (lr=0.0005), train loss 0.00053, GPU: 4016.0/8187.5 MiB
Epoch 8/200 (lr=0.0005), train loss 0.00049, GPU: 4016.0/8187.5 MiB
Epoch 9/200 (lr=0.0005), train loss 0.00046, GPU: 4016.0/8187.5 MiB
Training for epoch 10 done, starting evaluation
Epoch 10/200 (lr=0.0005), train loss 0.00045, valid loss 0.00033, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.32
  metrics/test.rmse_pcutoff:   1.29
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 11/200 (lr=0.0005), train loss 0.00043, GPU: 4016.0/8187.5 MiB
Epoch 12/200 (lr=0.0005), train loss 0.00039, GPU: 4016.0/8187.5 MiB
Epoch 13/200 (lr=0.0005), train loss 0.00044, GPU: 4016.0/8187.5 MiB
Epoch 14/200 (lr=0.0005), train loss 0.00040, GPU: 4016.0/8187.5 MiB
Epoch 15/200 (lr=0.0005), train loss 0.00041, GPU: 4016.0/8187.5 MiB
Epoch 16/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 17/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 18/200 (lr=0.0005), train loss 0.00036, GPU: 4016.0/8187.5 MiB
Epoch 19/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Training for epoch 20 done, starting evaluation
Epoch 20/200 (lr=0.0005), train loss 0.00035, valid loss 0.00019, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.97
  metrics/test.rmse_pcutoff:   0.96
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 21/200 (lr=0.0005), train loss 0.00038, GPU: 4016.0/8187.5 MiB
Epoch 22/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 23/200 (lr=0.0005), train loss 0.00037, GPU: 4016.0/8187.5 MiB
Epoch 24/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 25/200 (lr=0.0005), train loss 0.00033, GPU: 4016.0/8187.5 MiB
Epoch 26/200 (lr=0.0005), train loss 0.00035, GPU: 4016.0/8187.5 MiB
Epoch 27/200 (lr=0.0005), train loss 0.00034, GPU: 4016.0/8187.5 MiB
Epoch 28/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 29/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Training for epoch 30 done, starting evaluation
Epoch 30/200 (lr=0.0005), train loss 0.00030, valid loss 0.00024, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.17
  metrics/test.rmse_pcutoff:   1.16
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 31/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 32/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 33/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 34/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Epoch 35/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 36/200 (lr=0.0005), train loss 0.00031, GPU: 4016.0/8187.5 MiB
Epoch 37/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 38/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 39/200 (lr=0.0005), train loss 0.00032, GPU: 4016.0/8187.5 MiB
Training for epoch 40 done, starting evaluation
Epoch 40/200 (lr=0.0005), train loss 0.00029, valid loss 0.00020, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.00
  metrics/test.rmse_pcutoff:   1.00
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 41/200 (lr=0.0005), train loss 0.00030, GPU: 4016.0/8187.5 MiB
Epoch 42/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 43/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 44/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 45/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 46/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 47/200 (lr=0.0005), train loss 0.00029, GPU: 4016.0/8187.5 MiB
Epoch 48/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 49/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Training for epoch 50 done, starting evaluation
Epoch 50/200 (lr=0.0005), train loss 0.00027, valid loss 0.00018, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.94
  metrics/test.rmse_pcutoff:   0.94
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 51/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 52/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 53/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 54/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 55/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 56/200 (lr=0.0005), train loss 0.00028, GPU: 4016.0/8187.5 MiB
Epoch 57/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 58/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 59/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Training for epoch 60 done, starting evaluation
Epoch 60/200 (lr=0.0005), train loss 0.00026, valid loss 0.00017, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.89
  metrics/test.rmse_pcutoff:   0.88
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 61/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 62/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 63/200 (lr=0.0005), train loss 0.00027, GPU: 4016.0/8187.5 MiB
Epoch 64/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 65/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 66/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 67/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 68/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 69/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Training for epoch 70 done, starting evaluation
Epoch 70/200 (lr=0.0005), train loss 0.00024, valid loss 0.00020, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           1.06
  metrics/test.rmse_pcutoff:   1.06
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 71/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 72/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 73/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 74/200 (lr=0.0005), train loss 0.00026, GPU: 4016.0/8187.5 MiB
Epoch 75/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 76/200 (lr=0.0005), train loss 0.00025, GPU: 4016.0/8187.5 MiB
Epoch 77/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 78/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 79/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Training for epoch 80 done, starting evaluation
Epoch 80/200 (lr=0.0005), train loss 0.00022, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.79
  metrics/test.rmse_pcutoff:   0.79
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 81/200 (lr=0.0005), train loss 0.00024, GPU: 4016.0/8187.5 MiB
Epoch 82/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 83/200 (lr=0.0005), train loss 0.00023, GPU: 4016.0/8187.5 MiB
Epoch 84/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 85/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 86/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 87/200 (lr=0.0005), train loss 0.00022, GPU: 4016.0/8187.5 MiB
Epoch 88/200 (lr=0.0005), train loss 0.00021, GPU: 4016.0/8187.5 MiB
Epoch 89/200 (lr=0.0005), train loss 0.00020, GPU: 4016.0/8187.5 MiB
Training for epoch 90 done, starting evaluation
Epoch 90/200 (lr=0.0001), train loss 0.00021, valid loss 0.00013, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.85
  metrics/test.rmse_pcutoff:   0.85
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 91/200 (lr=0.0001), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 92/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 93/200 (lr=0.0001), train loss 0.00016, GPU: 4016.0/8187.5 MiB
Epoch 94/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 95/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 96/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 97/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 98/200 (lr=0.0001), train loss 0.00014, GPU: 4016.0/8187.5 MiB
Epoch 99/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Training for epoch 100 done, starting evaluation
Epoch 100/200 (lr=0.0001), train loss 0.00013, valid loss 0.00009, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.66
  metrics/test.rmse_pcutoff:   0.66
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 101/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 102/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 103/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 104/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 105/200 (lr=0.0001), train loss 0.00013, GPU: 4016.0/8187.5 MiB
Epoch 106/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 107/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 108/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 109/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Training for epoch 110 done, starting evaluation
Epoch 110/200 (lr=0.0001), train loss 0.00012, valid loss 0.00012, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.85
  metrics/test.rmse_pcutoff:   0.85
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 111/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 112/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 113/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 114/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 115/200 (lr=0.0001), train loss 0.00012, GPU: 4016.0/8187.5 MiB
Epoch 116/200 (lr=0.0001), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 117/200 (lr=0.0001), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 118/200 (lr=0.0001), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 119/200 (lr=0.0001), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Training for epoch 120 done, starting evaluation
Epoch 120/200 (lr=1e-05), train loss 0.00011, valid loss 0.00010, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.72
  metrics/test.rmse_pcutoff:   0.72
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 121/200 (lr=1e-05), train loss 0.00011, GPU: 4016.0/8187.5 MiB
Epoch 122/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 123/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 124/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 125/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 126/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 127/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 128/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 129/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Training for epoch 130 done, starting evaluation
Epoch 130/200 (lr=1e-05), train loss 0.00010, valid loss 0.00009, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.69
  metrics/test.rmse_pcutoff:   0.69
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 131/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 132/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 133/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 134/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 135/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 136/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 137/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 138/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 139/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Training for epoch 140 done, starting evaluation
Epoch 140/200 (lr=1e-05), train loss 0.00010, valid loss 0.00009, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.68
  metrics/test.rmse_pcutoff:   0.68
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 141/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 142/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 143/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 144/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 145/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 146/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 147/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 148/200 (lr=1e-05), train loss 0.00009, GPU: 4016.0/8187.5 MiB
Epoch 149/200 (lr=1e-05), train loss 0.00009, GPU: 4016.0/8187.5 MiB
Training for epoch 150 done, starting evaluation
Epoch 150/200 (lr=1e-05), train loss 0.00010, valid loss 0.00008, GPU: 4016.0/8187.5 MiB
Model performance:
  metrics/test.rmse:           0.65
  metrics/test.rmse_pcutoff:   0.65
  metrics/test.mAP:          100.00
  metrics/test.mAR:          100.00
Epoch 151/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 152/200 (lr=1e-05), train loss 0.00009, GPU: 4016.0/8187.5 MiB
Epoch 153/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 154/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 155/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 156/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB
Epoch 157/200 (lr=1e-05), train loss 0.00010, GPU: 4016.0/8187.5 MiB

  ERROR: No snapshots found under pattern: C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\DeepLabCut\Endive\TestData\Canari_combined_n1400\Canari-Tyler-2026-04-08\dlc-models-pytorch\iteration-0\*\train\snapshots\snapshot-*.pt

────────────────────────────────────────────────────────────
Training runs recorded: 8

         bird  nframes architecture  trained  train_time_s
0  DavidBowie      200    resnet_50    False        3648.2
1  DavidBowie      400    resnet_50    False        7162.0
2  DavidBowie      800    resnet_50    False       14416.9
3  DavidBowie     1400    resnet_50    False       25569.8
4      Endive      200    resnet_50    False        3649.7
5      Endive      400    resnet_50    False        8491.6
6      Endive      800    resnet_50    False       14469.8
7      Endive     1400    resnet_50    False       25427.9

### Model Manipulation

How are we able to pull and train specific layers of the model to improve/transfer